version: '2.0'
services:
  app:
    tty: true      
    build:
      context: .
      dockerfile: ./Dockerfile.deploy
      args:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY    
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ENVIRONMENT: ${ENVIRONMENT}
      EC2_KEY_NAME: ${EC2_KEY_NAME}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


    

   
      