service: queue-worker

plugins:
  - serverless-functions-base-path # this allows us to use the src directory structure which makes it easier in a monorepo

custom:
  functionsBasePath: src # this is where we tell it what dir to use

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${file(../../serverless.common.yml):stage} # stage is shared among all packages so we use the common.yml to set
  region: ${file(../../serverless.common.yml):region} # region is shared among all packages so we use the common.yml to set

# environment: 
# some key:val here, if you declare here all functions will get these vars, you can set individually in the functions themselves too

functions:
  sqsWorker:
    handler: handler.handler
    timeout: 30
    events:
      - sqs: 
          arn:
              Fn::ImportValue: "${self:provider.stage}:SqsQueueArn"
    